# Generated by Django 4.1.7 on 2023-03-24 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
        migrations.RemoveField(
            model_name='account',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
    ]
